### ISSUE TITLE
parse_alias like function

### ISSUE THREAD

**Issue by orhanbalci** [orhanbalci/emojic#11]
Currently parse_alias only performs a lookup. We need a function which will perform find and replace in a given string.

**Comment by Cryptjar** [comment]
Do mean like replacing a string such as
```text
Hello :waving_hand:, I am a :technologist:.
```
with
```text
Hello 👋, I am a 👨‍💻.
```
By searching for `:[a-z_]+:` (regex) within the input text and replace all these occurrences via the current `parse_alias` function?

**Comment by orhanbalci** [comment]
Correct
