### ISSUE TITLE
Subdividing the Emojis into Multiple Modules

### ISSUE THREAD

**Issue by Cryptjar** [orhanbalci/emojic#2]
I notice that during the code generation for the `constants.rs` (which contains all the emojis) that all emojis are categorized into groups and subgroups. Now, wonder whether it would be beneficial to use these groups to organize the emojis into respective modules. For instance a fully qualified version of the example in the readme could look like the following:

```rust
println!("Hello {}", emojic::constants::people_and_body::hand_fingers_open::WAVING_HAND);
println!(
    "I'm {} from {}",
    emojic::constants::people_and_body::person_role::MAN_TECHNOLOGIST,
    emojic::constants::flags::country_flag::FLAG_TURKEY
);
```

I'm not sure whether this would really increase the usability, but it would definitely tidy up the API documentation, which currently lists all nearly 2k emojis in a single module. As a compromise, one could also introduce an `all` (or something) module, which then contains a `pub use` for every emoji from all categories (i.e. modules) acting as a shortcut (e.g. `emojic::all::MAN_TECHNOLOGIST`).

**Comment by orhanbalci** [comment]
Lets think about usability. If I want to use `MAN_TECHNOLOGIST` if we devide into modules than I need to know where `MEN_TECHNOLOGIST` is (`people_and_body::person_role`). I think this is a tedious work.  But introducing `all` module changes  this. If we introduce modules we definitely should include an `all` module.

**Comment by Cryptjar** [comment]
Depending on your willingness for breaking changes, we could also reduce the module depth in the API by removing the `constants` module, which ironically contains `static`s. So that fully qualified names start at the crate root: `emojic::people_and_body::person_role::MAN_TECHNOLOGIST` and shortcuts could be in a single root level module: `emojic::all::MAN_TECHNOLOGIST`.

Personally, I would also move the functions and types defined in `alias.rs` and `constants.rs` into the `lib.rs` so that the generated files `alias.rs` and `constants.rs` only contain generated code (i.e. only the hash map and the list of statics, respectively), and these types and functions are easier to maintain.

---

As side note, is there a reason why the 'constants' are `static`s instead of `const`s?

**Comment by orhanbalci** [comment]
EmojiWithTone methods needs mut reference so const is not possible

**Comment by Cryptjar** [comment]
> EmojiWithTone methods needs mut reference so const is not possible

Actually, you can't get a mutable reference to a `static` either (except if it is declared `static mut` and using `unsafe`). And I don't see any method on `EmojiWithTone` that takes `&mut self` (a mutable reference). The next best might be the chain-constructors, which take a `mut self`, but that is not a reference, it is passed-by-value and only mutable within the respective function (since it is a local variable). Also, these constructors will run at compile time (which is required for values assigned to `static` & `const` alike), so the `static` itself is never accessed mutably. In fact, if I just rewrite the code generator to produce `const`s instead, it works just fine for me.

Typically, the differences between `static` & `const` in Rust are somewhat subtle, in many cases both work very similarly (like in this case). The biggest difference is if one needs a stable addresses/references to a value (e.g. `&'static T`) or mutability (including interior mutability through mutex & atomics).
Also see https://stackoverflow.com/a/65475478 for a more detailed discussion.

**Comment by orhanbalci** [comment]
If you like to work on restructuring the modules you are welcome. According to crates.io no other crate is depending on this one right now.

**Comment by orhanbalci** [comment]
By the way if you like you can add yourself to authors section of the cargo.toml file.

**Comment by Cryptjar** [comment]
> By the way if you like you can add yourself to authors section of the cargo.toml file.

Yes that is a good idea, I add an PR for that soon.
