### ISSUE TITLE
Update readme file with the new API changes

### ISSUE THREAD

**Issue by orhanbalci** [orhanbalci/emojic#5]
README file is a bit old. Does not include new API changes.

**Comment by Cryptjar** [comment]
Yes that's true. In this context, I noticed that currently the `lib.rs` doesn't have a crate-level documentation yet. I personally would write there the same as in the README (and vice versa) essentially syncing the crate-level doc with the README file. For this syncing, there exist also some nice tools to do the copy past stuff such as:
- [`cargo-readme`](https://crates.io/crates/cargo-readme) 
- [`cargo-sync-readme`](https://crates.io/crates/cargo-sync-readme)

I used both in the past and work well, the basic difference is that `cargo-readme` uses a template README file where it inserts the crate-level doc, whereas `cargo-sync-readme` uses HTML comments directly in the final README which indicate what sections were included from the crate-level doc and thus which needs to be updated.

**Comment by Cryptjar** [comment]
If you like, I can add the updated content of the current README to the `lib.rs` and set up the syncing, thus updating the README in the process, too.

**Comment by orhanbalci** [comment]
Yes please

**Comment by Cryptjar** [comment]
Good, I have just a few features which I would like to implement first, thereafter I will make a PR for the README.

**Comment by orhanbalci** [comment]
country_flag and regional_flag examples would be nice to have in readme. I appreciate your work by the way :+1:

**Comment by Cryptjar** [comment]
Sure, you're welcome.

**Comment by orhanbalci** [comment]
I think we are done with this.
